import io
from datetime import datetime
from decimal import Decimal, InvalidOperation
from html import escape
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, KeepTogether
from app.schemas.operation import OperationRead

def _format_decimal(value: Decimal | str | int | float | None) -> str:
    if value is None:
        return "-"
    try:
        d = Decimal(str(value))
        return "{:,.2f}".format(d)
    except (InvalidOperation, ValueError, TypeError):
        return str(value)

def _format_datetime(value: datetime | None) -> str:
    if value is None:
        return "-"
    return value.strftime("%d-%m-%Y")

def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setStrokeColor(colors.grey)
    canvas.line(2*cm, 1.5*cm, 19*cm, 1.5*cm)
    
    canvas.drawString(2*cm, 1.1*cm, "Generated by CoreInventory")
    canvas.drawRightString(19*cm, 1.1*cm, f"Page {doc.page}")
    canvas.restoreState()

def generate_invoice_pdf(op: OperationRead) -> io.BytesIO:
    op_type_str = str(op.type.value if hasattr(op.type, 'value') else op.type).upper()
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=A4, 
        rightMargin=2*cm, 
        leftMargin=2*cm, 
        topMargin=2*cm, 
        bottomMargin=2*cm
    )
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#534AB7"),
        spaceAfter=20
    )
    
    elements = []

    # 1. Title
    if op_type_str == "RECEIPT":
        op_title = "RECEIPT INVOICE"
    elif op_type_str == "DELIVERY":
        op_title = "DELIVERY NOTE"
    elif op_type_str == "INTERNAL":
        op_title = "INTERNAL TRANSFER"
    elif op_type_str == "ADJUSTMENT":
        op_title = "STOCK ADJUSTMENT"
    else:
        op_title = f"INVENTORY OPERATION ({op_type_str})"
    
    elements.append(Paragraph(escape(op_title), title_style))
    
    # 2. Header Table (Ref & Date)
    operation_date = op.scheduled_date or op.created_at
    header_data = [
        ["Reference:", op.reference, "Date:", _format_datetime(operation_date)],
        ["Status:", op.status.upper(), "Type:", op_type_str],
    ]
    header_t = Table(header_data, colWidths=[3*cm, 6*cm, 3*cm, 5*cm])
    header_t.setStyle(TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('TEXTCOLOR', (0,0), (0,-1), colors.grey),
        ('TEXTCOLOR', (2,0), (2,-1), colors.grey),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
    ]))
    elements.append(header_t)
    elements.append(Spacer(1, 0.5*cm))

    # 3. Address Table
    sender_name, sender_address, sender_label = "-", "-", "From"
    receiver_name, receiver_address, receiver_label = "-", "-", "To"

    if op_type_str == "RECEIPT":
        sender_name = op.supplier_name or op.supplier or "-"
        sender_address = op.supplier_address or "-"
        sender_label = "From (Supplier)"
        receiver_name = op.dest_warehouse_name or "-"
        receiver_address = op.dest_warehouse_address or "-"
        receiver_label = "To (Warehouse)"
    elif op_type_str == "DELIVERY":
        sender_name = op.src_warehouse_name or "-"
        sender_address = op.src_warehouse_address or "-"
        sender_label = "From (Warehouse)"
        receiver_name = op.customer_name or op.customer or "-"
        receiver_address = op.customer_address or "-"
        receiver_label = "To (Customer)"
    else:
        sender_name = op.src_warehouse_name or "-"
        sender_address = op.src_warehouse_address or "-"
        receiver_name = op.dest_warehouse_name or "-"
        receiver_address = op.dest_warehouse_address or "-"

    safe_s_addr = escape(sender_address or "-").replace('\n', '<br/>')
    safe_r_addr = escape(receiver_address or "-").replace('\n', '<br/>')
    
    address_data = [
        [Paragraph(f"<b>{escape(sender_label)}</b>", styles['Normal']), Paragraph(f"<b>{escape(receiver_label)}</b>", styles['Normal'])],
        [Paragraph(escape(sender_name or "-"), styles['Normal']), Paragraph(escape(receiver_name or "-"), styles['Normal'])],
        [Paragraph(safe_s_addr, styles['Normal']), Paragraph(safe_r_addr, styles['Normal'])],
    ]
    address_t = Table(address_data, colWidths=[8.5*cm, 8.5*cm])
    address_t.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'TOP'), ('BOTTOMPADDING', (0,0), (-1,-1), 5)]))
    elements.append(address_t)
    elements.append(Spacer(1, 1*cm))

    # 4. Product Table
    move_data = [["SKU", "Product", "From", "To", "Demand", "Done"]]
    for m in op.moves:
        move_data.append([
            escape(m.product_sku),
            escape(m.product_name),
            escape(m.src_location_name or "-"),
            escape(m.dest_location_name or "-"),
            f"{_format_decimal(m.demand_qty)} {escape(m.product_uom)}",
            f"{_format_decimal(m.done_qty) if m.done_qty is not None else '-'} {escape(m.product_uom)}"
        ])

    moves_table = Table(move_data, colWidths=[2.5*cm, 5.5*cm, 2.5*cm, 2.5*cm, 2.0*cm, 2.0*cm], repeatRows=1)
    moves_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#534AB7")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('FONTSIZE', (0,0), (-1,0), 10),
        ('FONTSIZE', (0,1), (-1,-1), 9),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
    ]))
    elements.append(moves_table)
    
    if op.notes:
        elements.append(Spacer(1, 1*cm))
        elements.append(Paragraph("<b>Notes:</b>", styles['Normal']))
        elements.append(Paragraph(escape(op.notes), styles['Normal']))

    # 5. Signature Section (The part that was missing in your screenshot)
    elements.append(Spacer(1, 2*cm))
    sig_data = [
        ["Prepared By", "", "Received / Authorized By"],
        ["", "", ""],
        ["________________________", "", "________________________"],
        ["Signature & Date", "", "Stamp / Signature & Date"]
    ]
    sig_table = Table(sig_data, colWidths=[7*cm, 3*cm, 7*cm])
    sig_table.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'BOTTOM'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,1), (0,1), 40), 
        ('BOTTOMPADDING', (2,1), (2,1), 40),
    ]))
    elements.append(KeepTogether([sig_table]))

    try:
        doc.build(elements, onFirstPage=_footer, onLaterPages=_footer)
    except Exception as e:
        buffer = io.BytesIO()
        doc_err = SimpleDocTemplate(buffer, pagesize=A4)
        doc_err.build([Paragraph(f"Error: {str(e)}", styles['Normal'])])
    
    buffer.seek(0)
    return buffer
