"""description

Revision ID: 4ab1348272c4
Revises: 
Create Date: 2026-03-14 14:26:36.027790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ab1348272c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
