"""add_user_id_to_operation

Revision ID: e3e6c0d46945
Revises: 4ab1348272c4
Create Date: 2026-03-17 10:53:50.076323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3e6c0d46945'
down_revision: Union[str, None] = '4ab1348272c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_operations_created_at'), 'operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_operations_user_id'), 'operations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'operations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_index(op.f('ix_operations_user_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_created_at'), table_name='operations')
    op.drop_column('operations', 'user_id')
    # ### end Alembic commands ###
